
[[tm]]
  ip = "106.3.133.178"
  isNew = false

[[tm]]
  ip = "106.3.133.179"
  isNew = false

[[tm]]
  ip = "106.3.133.180"
  isNew = false

[[tm]]
  ip = "210.73.218.171"
  isNew = false

[[tm]]
  ip = "210.73.218.172"
  isNew = false

[[tm]]
  ip = "101.251.223.190"
  isNew = false

[[bsc]]
  ip = "106.3.133.178"
  isNew = false

[[bsc]]
  ip = "106.3.133.179"
  isNew = false

[[bsc]]
  ip = "106.3.133.180"
  isNew = false

[[bsc]]
  ip = "210.73.218.171"
  isNew = false

[[bsc]]
  ip = "210.73.218.172"
  isNew = false

[[bsc]]
  ip = "101.251.223.190"
  isNew = false

[server]
  token = "3D3781351A3EE9E4"

[tm-server]
  ip = "210.73.218.171"
[monitor]
  ding-url = "https://oapi.dingtalk.com/robot/send?access_token=cf2758d4b768f7aa352a919c72f88e9e9fd695168147f851c38c7a78d92cbd69"
  prefix-key = "tm异常:"
  interval = 5
  retry-times = 5
  abnormal-hosts = []