
[[tm]]

  # ip地址
  ip = "106.3.133.178"

  # 用于确定是否为新加ip,默认为false,已弃用
  isNew = false

[[tm]]

  # ip地址
  ip = "106.3.133.179"

  # 用于确定是否为新加ip,默认为false,已弃用
  isNew = false

[[tm]]

  # ip地址
  ip = "106.3.133.180"

  # 用于确定是否为新加ip,默认为false,已弃用
  isNew = false

[[tm]]

  # ip地址
  ip = "210.73.218.171"

  # 用于确定是否为新加ip,默认为false,已弃用
  isNew = false

[[tm]]

  # ip地址
  ip = "210.73.218.172"

  # 用于确定是否为新加ip,默认为false,已弃用
  isNew = false

[[tm]]

  # ip地址
  ip = "101.251.223.190"

  # 用于确定是否为新加ip,默认为false,已弃用
  isNew = false

[[bsc]]

  # ip地址
  ip = "106.3.133.178"

  # 用于确定是否为新加ip,默认为false,已弃用
  isNew = false

[[bsc]]

  # ip地址
  ip = "106.3.133.179"

  # 用于确定是否为新加ip,默认为false,已弃用
  isNew = false

[[bsc]]

  # ip地址
  ip = "106.3.133.180"

  # 用于确定是否为新加ip,默认为false,已弃用
  isNew = false

[[bsc]]

  # ip地址
  ip = "210.73.218.171"

  # 用于确定是否为新加ip,默认为false,已弃用
  isNew = false

[[bsc]]

  # ip地址
  ip = "210.73.218.172"

  # 用于确定是否为新加ip,默认为false,已弃用
  isNew = false

[[bsc]]

  # ip地址
  ip = "101.251.223.190"

  # 用于确定是否为新加ip,默认为false,已弃用
  isNew = false

# bsc链server配置
[server]

  # bsc链server token
  token = "3D3781351A3EE9E4"

# tm链server ip
[tm-server]
  ip = "210.73.218.171"

# tm落后节点监视器
[monitor]

  # 钉钉机器人接口
  ding-url = "https://oapi.dingtalk.com/robot/send?access_token=cf2758d4b768f7aa352a919c72f88e9e9fd695168147f851c38c7a78d92cbd69"

  # 钉钉安全,消息前缀
  prefix-key = "tm异常:"

  # 获取块高时间间隔,单位为秒
  interval = 5

  # 判断区块落后所需次数
  retry-times = 5

  # 落后区块节点ip列表
  abnormal-hosts = []
